DROP DATABASE IF EXISTS rekrutacja;
CREATE DATABASE IF NOT EXISTS rekrutacja DEFAULT CHARACTER SET = 'utf8';
USE rekrutacja;

CREATE TABLE logowanie (
  EMAIL VARCHAR(50),
  HASLO VARCHAR(255),
  PRIMARY KEY (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE adresy (
  ID_ADRES INT AUTO_INCREMENT, 
  WOJEWODZTWO VARCHAR(50),
  MIEJSCOWOSC VARCHAR(50),
  KOD_POCZTOWY VARCHAR(7),
  ULICA VARCHAR(50),
  NR_DOMU VARCHAR(4),
  NR_MIESZKANIA INT(3),
  PRIMARY KEY (ID_ADRES)
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE pracownicy (
  ID_PRAC INT AUTO_INCREMENT,
  IMIE VARCHAR(30),
  NAZWISKO VARCHAR(30),
  PLEC ENUM('M', 'K'),
  DATA_URODZENIA DATE,
  PESEL VARCHAR(11),
  EMAIL VARCHAR(50),
  ID_ADRES INT,
  PRIMARY KEY (ID_PRAC),
  CONSTRAINT FK_logowanie_pracownicy FOREIGN KEY (EMAIL) REFERENCES logowanie(EMAIL) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_adres_pracownicy FOREIGN KEY (ID_ADRES) REFERENCES adresy(ID_ADRES) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE kandydaci (
  ID_KAND INT AUTO_INCREMENT,
  IMIE VARCHAR(30),
  NAZWISKO VARCHAR(30),
  PLEC ENUM('M', 'K'),
  DATA_URODZENIA DATE,
  PESEL VARCHAR(11),
  EMAIL VARCHAR(50),
  ID_ADRES INT,
  PRIMARY KEY (ID_KAND),
  CONSTRAINT FK_logowanie_kandydaci FOREIGN KEY (EMAIL) REFERENCES logowanie(EMAIL) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_adres_kandydaci FOREIGN KEY (ID_ADRES) REFERENCES adresy(ID_ADRES) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE punkty (
  ID_KAND INT,
  MAT_FIZ_INF DECIMAL(5,2),
  HUMAN DECIMAL(5,2),
  SPORT DECIMAL(5,2),
  BIOL_CHEM DECIMAL(5,2),
  PRIMARY KEY (ID_KAND),
  CONSTRAINT FK_kandydaci_punkty FOREIGN KEY (ID_KAND) REFERENCES kandydaci(ID_KAND) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE oceny (
  ID_KAND INT,
  POLSKI INT(1),
  OBCY INT(1),
  HISTORIA INT(1),
  MATEMATYKA INT(1),
  FIZYKA INT(1),
  BIOLOGIA INT(1),
  CHEMIA INT(1),
  WF INT(1),
  PASEK ENUM('T', 'N'),
  PRIMARY KEY (ID_KAND),
  CONSTRAINT FK_kandydaci_oceny FOREIGN KEY (ID_KAND) REFERENCES kandydaci(ID_KAND) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE egzaminy (
  ID_KAND INT,
  POLSKI INT(3),
  HISTORIA INT(3),
  MATEMATYKA INT(3),
  PRZYRODNICZE INT(3),
  OBCY_PODSTAWA INT(3),
  PRIMARY KEY (ID_KAND),
  CONSTRAINT FK_kandydaci_egzaminy FOREIGN KEY (ID_KAND) REFERENCES kandydaci(ID_KAND) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';

CREATE TABLE wybory (
  ID_KAND INT,
  PIERWSZY VARCHAR(15),
  DRUGI VARCHAR(15),
  TRZECI VARCHAR(15),
  PRIMARY KEY (ID_KAND),
  CONSTRAINT FK_kandydaci_wybory FOREIGN KEY (ID_KAND) REFERENCES kandydaci(ID_KAND) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET='utf8';